apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: drone-master
  name: drone-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drone05
        tier: frontend
    spec:
      containers:
      - name: master
        image: drone/drone:0.5
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: DRONE_GITHUB_CLIENT
          value: super_secret_client
        - name: DRONE_GITHUB_SECRET
          value: super_secret_secret
        - name: DRONE_GITHUB
          value: "true"
        - name: DRONE_SECRET
          value: drone_secret
        - name: DRONE_OPEN
          value: "false"
        - name: DRONE_ADMIN
          value: gjtempleton,octocat
        ports:
        - containerPort: 80
