apiVersion: v1
kind: Service
metadata:
  name: drone-master
  labels:
    app: drone
    role: master
    tier: frontend
    name: drone-master
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: drone05
    tier: frontend
